name: fintrack
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  firebase_auth: ^6.1.4
  firebase_core: ^4.4.0
  firebase_database: ^12.1.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  font_awesome_flutter: ^10.12.0
  go_router: ^17.0.1
  google_fonts: ^7.1.0
  riverpod_annotation: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  custom_lint: ^0.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/