name: fintrack
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  currency_picker: ^2.0.21
  firebase_auth: ^6.1.4
  firebase_core: ^4.4.0
  firebase_database: ^12.1.2
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  font_awesome_flutter: ^10.12.0
  go_router: ^17.0.1
  google_fonts: ^7.1.0
  google_sign_in: ^7.2.0
  intl: ^0.20.2
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.5.4
  supabase_flutter: ^2.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  custom_lint: ^0.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/